export const ShopProductsPage = {
    menubar:{
        typeSearchInput: "//div[@class='input-row flex align-items-center ']/input[@name='s']",
        searchButton: "//div[@class='input-row flex align-items-center ']//button",
        searchButtonText: "//button[@class='search-submit']/span",
        name: "//input[@id='me_name']",
        email: "//input[@id='me_email']",
        subject: "//input[@id='me_subject']",
        message: "//textarea[@id='me_message']",
    },
    filterList:{
        filterSelect: "//select[@name='orderby']",
        filterGroup: "//input[@id='me_subject']",
        filterGroupButton: "//button[@name='send']",
        filterGroupButtonText: "//button[@name='send']/span",
        filterGroupButtonTextContent: "Send Message",
    },
    productsList: {
        productName: "//h2[@class='woocommerce-loop-product__title']",
        productPrice: "//span[@class='woocommerce-Price-amount amount']",
        productAddToCartButton: "//button[@name='add-to-cart']",
    },
    productdetails: {
        productTitle: "//h1[@class='product_title entry-title']",
        productPrice: "//p[@class='price']",
        productDescription: "//div[@class='woocommerce-product-details__short-description']",
        productAddToCartButton: "//button[@class='add_to_cart_button ajax_add_to_cart single_add_to_cart_button button alt']",
        productQuantity: "//input[@name='quantity']",
        productSize: "//select[@name='attribute_pa_size']",
        productColor: "//select[@name='attribute_pa_color']",
        productAddToCartSuccessMessage: "//div[@class='woocommerce-message']",
        productReviewTab: "//div/ul//a[@id='tab_reviews']",
        productDescriptionTab: "//div/ul//a[@id='tab_description']",
        yourProductRating: "//p//a[.='5']",
        yourProductReview: "//textarea[@id='comment']",
        yourNameReview: "//p//input[@id='author']",
        yourEmailReview: "//p//input[@id='email']",
        yourSaveReview: "//p[@class='comment-form-cookies-consent']/input",
        yourSubmitReview: "//p//input[@id='submit']",
    },
    contactForm: {  
        contactFromTitle: "//h2[contains(text(),'Contact Us')]",
        contactDetailsTitle: "//p[contains(text(),'We are here to help you with any questions or concerns you may have.')]",
        submitSendMessageButton: "//button[@name='send']",
        messageSentText: "//div[@class='woocommerce-message']",
        supportCenterSpan: "//span[contains(text(),'Support Center')]",
        yourNameInput: "//input[@id='me_name']",
        yourEmailInput: "//input[@id='me_email']",
        subjectInput: "//input[@id='me_subject']",
        yourMessageInput: "//textarea[@id='me_message']",
    }
};